### ISSUE TITLE
Menu hover effect

### ISSUE THREAD

**Issue by brendon-avalos** [johnlewissims/symbiosis#18]
would be great to be able to have the primary nav items show a hover effect when scrolled over them. Design attached
<img width="1328" alt="Screen Shot 2022-07-11 at 3 23 51 PM" src="https://user-images.githubusercontent.com/57079598/178342295-d4c2b866-5d98-4d97-92bf-7dda2cb0f1ec.png">
.

**Comment by johnlewissims** [comment]
Merged into master!
