### ISSUE TITLE
Social Media Fields Added

### ISSUE THREAD

**Issue by johnlewissims** [johnlewissims/symbiosis#19]
These need to be global settings

**Comment by brendon-avalos** [comment]
@johnlewissims 

I am still not seeing social media icons on articles. Is it an asset problem or something that you need to add in?
<img width="1413" alt="Screen Shot 2022-08-10 at 11 17 41 PM" src="https://user-images.githubusercontent.com/57079598/184059555-3f5ec37f-5b38-4d2e-9a4c-727bcf0d5daf.png">

**Comment by brendon-avalos** [comment]
I imagined these links being "share" links. Like they integrate with the platforms to share the article. If this is too much then we can just kill it and maybe its a "copy" link button. If that is too much then I can figure out a design solution. 

@johnlewissims

**Comment by johnlewissims** [comment]
<img width="1025" alt="Screen Shot 2022-09-03 at 9 56 11 AM" src="https://user-images.githubusercontent.com/43911794/188278510-351d3814-7b55-4312-b0c9-8ff75958a286.png">

I bet that the assets are missing. See if this asset loads on your machine...

/wp-content/uploads/2022/07/facebook2x.png

@brendon-avalos

**Comment by brendon-avalos** [comment]
@johnlewissims I got them to load. Let me know how you feel about making them "share" page links instead of just links to overall social media.

**Comment by johnlewissims** [comment]
Ahhh now I see the issue. Ok, added that to the most recent commit
