### ISSUE TITLE
Cards Fixed Image SIzes

### ISSUE THREAD

**Issue by brendon-avalos** [johnlewissims/symbiosis#22]
<img width="1108" alt="Screen Shot 2022-07-14 at 10 11 49 AM" src="https://user-images.githubusercontent.com/57079598/179003001-edec26ea-4e86-4877-816f-2cfbfd70d214.png">

Nice to have 2 variations of cropped/fixed image sizes for the cards.

**Image Variations**
Square 4:4 
Rectangle 3:4
None

**Comment by johnlewissims** [comment]
How will we determine which one will be which size? Should we just alternate? @brendon-avalos

**Comment by brendon-avalos** [comment]
We can remove this feature. If we can select articles for the homepage I can just curate the thumbnails. :)
