### ISSUE TITLE
Article Stacking Bug

### ISSUE THREAD

**Issue by brendon-avalos** [johnlewissims/symbiosis#38]
<img width="1301" alt="Screen Shot 2022-09-02 at 11 33 06 AM" src="https://user-images.githubusercontent.com/57079598/188184254-21285415-026b-4f0a-99db-b3eac3be1fae.png">

This overlap bug still happens on page load.

**Comment by johnlewissims** [comment]
This should be resolved once we minify. If we see it in stage then we can re-open.
