### ISSUE TITLE
Blog Card - Work Without Feature Image

### ISSUE THREAD

**Issue by brendon-avalos** [johnlewissims/symbiosis#4]
<img width="557" alt="Screen Shot 2022-07-07 at 8 03 47 PM" src="https://user-images.githubusercontent.com/57079598/177890938-f5f9f41c-91ef-4d1a-b4d4-cc56fe636ad2.png">
Even if there is no "feature image" we should have the cards display without "missing picture" icon"

**Comment by johnlewissims** [comment]
@brendon-avalos Got it! Pull master to update.
