### ISSUE TITLE
Repeating content

### ISSUE THREAD

**Issue by brendon-avalos** [johnlewissims/symbiosis#44]
@johnlewissims 

I see repeating content on the approach and strategy pages.
They are using the same data in wordpress but just displaying one as unstyled.

<img width="1202" alt="Screen Shot 2022-09-03 at 4 55 21 PM" src="https://user-images.githubusercontent.com/57079598/188287416-ee63c90d-ee0c-42e6-bac5-b2e194ac372c.png">
<img width="1498" alt="Screen Shot 2022-09-03 at 4 55 36 PM" src="https://user-images.githubusercontent.com/57079598/188287418-a9ebf51c-e6b7-45fc-b24f-a23f8f1e9d23.png">

**Comment by johnlewissims** [comment]
Got it!
